services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: criar_web_challenge
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ./src:/var/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: criar_web_challenge_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-userpass}
      - MYSQL_USER=${DB_USERNAME:-user}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3308"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: criar_web_challenge_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    
networks:
  laravel:
    driver: bridge
    
volumes:
  dbdata: 
    driver: local